% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Trading ETF's, Daniel Emil Wiinberg S133232},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Trading ETF's, Daniel Emil Wiinberg S133232}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{setwd}\NormalTok{(}\StringTok{"/Users/dwiinberg/Documents/ETF\_Project/ETF\_Statistics/Project 1"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{D }\OtherTok{=} \FunctionTok{read.table}\NormalTok{(}\StringTok{"finans1\_data.csv"}\NormalTok{, }\AttributeTok{header=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{sep=}\StringTok{";"}\NormalTok{, }\AttributeTok{as.is=}\ConstantTok{TRUE}\NormalTok{)}
\NormalTok{D }\OtherTok{=}\NormalTok{ D[ ,}\FunctionTok{c}\NormalTok{(}\StringTok{"t"}\NormalTok{,}\StringTok{"AGG"}\NormalTok{,}\StringTok{"VAW"}\NormalTok{,}\StringTok{"IWN"}\NormalTok{,}\StringTok{"SPY"}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\section{Descriptive analysis}

The raw data includes weekly returns for 95 ETFs, with the first week
being 2006-5-5 and the last week being 2015-5-8 (date format is
yyyy-mm-dd). In total this is 454 data points for every ETF.

From this raw data four ETFs are selected, they are:

\begin{itemize}
\tightlist
\item
  AGG - iShares Core Total US Bond Market ETF
\item
  VAW - Vanguard Materials ETF
\item
  IWN - iShares Russell 2000 Value Index Fund
\item
  SPY - SPDR Trust, Series 1 is a unit investment trust
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(D)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           t          AGG         VAW          IWN          SPY
## 1  2006-5-5 -0.006088280  0.03157274  0.023603147  0.007986613
## 2 2006-5-12 -0.003675345 -0.02745995 -0.048071912 -0.024750981
## 3 2006-5-19  0.006660518 -0.05000000 -0.014096072 -0.016558341
## 4 2006-5-26  0.001832248  0.01253870  0.009716824  0.010070810
## 5  2006-6-5 -0.004775452 -0.02232075 -0.017734396 -0.009814613
## 6 2006-6-12  0.001225115 -0.06098514 -0.038348495 -0.024622404
\end{verbatim}

From the rows we can se that we are dealing with quantitative data (the
return of the ETF) and the week this return was given.

Looking through the data is can be seen that the data is complete for
the four ETF's selected. However tt can also be seen that SPY has an
outlier of -18, which looks to be wrong in comparison to the rest of the
data. But since it's just one datapoint out of 454, it won't have much
of an impact.

\subsection{Histogram}

Shown is a histogram of the empirical density of weekly return from the
AGG fund.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{AGG, }\AttributeTok{xlab=}\StringTok{"Return (AGG)"}\NormalTok{, }\AttributeTok{prob=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{breaks =} \DecValTok{50}\NormalTok{, }\AttributeTok{col=}\StringTok{"blue"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_finans_files/figure-latex/unnamed-chunk-4-1.pdf}

From the histogram it can be seen that the data is largely symmetrical,
with both positive and negative returns, as expected from the stock
market. The variations are between -0.03 and 0.03, with the largest
quantity being between -0.01 and 0.01.

\subsection{Return over time}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Setting the t{-}variable as a date variable.}
\NormalTok{D}\SpecialCharTok{$}\NormalTok{t }\OtherTok{=} \FunctionTok{as.Date}\NormalTok{(}\AttributeTok{x=}\NormalTok{D}\SpecialCharTok{$}\NormalTok{t, }\AttributeTok{format=}\StringTok{"\%Y{-}\%m{-}\%d"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Next we plot the weekly return over time for each of the four ETF's.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ylim }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\FloatTok{0.2}\NormalTok{,}\FloatTok{0.2}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{t, D}\SpecialCharTok{$}\NormalTok{AGG, }\AttributeTok{type=}\StringTok{"l"}\NormalTok{, }\AttributeTok{ylim=}\NormalTok{ylim, }\AttributeTok{xlab=}\StringTok{"Date"}\NormalTok{, }\AttributeTok{ylab=}\StringTok{"Return AGG"}\NormalTok{, }\AttributeTok{col=}\StringTok{"blue"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_finans_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{t, D}\SpecialCharTok{$}\NormalTok{VAW, }\AttributeTok{type=}\StringTok{"l"}\NormalTok{, }\AttributeTok{ylim=}\NormalTok{ylim, }\AttributeTok{xlab=}\StringTok{"Date"}\NormalTok{, }\AttributeTok{ylab=}\StringTok{"Return VAW"}\NormalTok{, }\AttributeTok{col=}\StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_finans_files/figure-latex/unnamed-chunk-6-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{t, D}\SpecialCharTok{$}\NormalTok{IWN, }\AttributeTok{type=}\StringTok{"l"}\NormalTok{, }\AttributeTok{ylim=}\NormalTok{ylim, }\AttributeTok{xlab=}\StringTok{"Date"}\NormalTok{, }\AttributeTok{ylab=}\StringTok{"Return IWN"}\NormalTok{, }\AttributeTok{col=}\StringTok{"green"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_finans_files/figure-latex/unnamed-chunk-6-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{t, D}\SpecialCharTok{$}\NormalTok{SPY, }\AttributeTok{type=}\StringTok{"l"}\NormalTok{, }\AttributeTok{ylim=}\NormalTok{ylim, }\AttributeTok{xlab=}\StringTok{"Date"}\NormalTok{, }\AttributeTok{ylab=}\StringTok{"Return SPY"}\NormalTok{, }\AttributeTok{col=}\StringTok{"orange"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_finans_files/figure-latex/unnamed-chunk-6-4.pdf}

From the plots it can be seen that they are clearly very different in
the return they provide. The least fluctuation can be seen in the AGG
fund, which is an ETF tracking the US bond market. Therefore it makes
sense that is has less fluctuation.

Besides that it can be seen for the other 3 funds that they have the
most fluctuation around 2009 and again in the last quarter of 2011.
Otherwise the weekly return fluctuates between -0.1 and 0.1 or less.

\subsection{Box plots}

Creating box plots for the four ETF's.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{AGG, D}\SpecialCharTok{$}\NormalTok{VAW, D}\SpecialCharTok{$}\NormalTok{IWN, D}\SpecialCharTok{$}\NormalTok{SPY, }\AttributeTok{names=}\FunctionTok{c}\NormalTok{(}\StringTok{"AGG"}\NormalTok{, }\StringTok{"VAW"}\NormalTok{, }\StringTok{"IWN"}\NormalTok{, }\StringTok{"SPY"}\NormalTok{),}
        \AttributeTok{xlab=}\StringTok{"ETF"}\NormalTok{, }\AttributeTok{ylab=}\StringTok{"Return"}\NormalTok{, }\AttributeTok{col=}\StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_finans_files/figure-latex/unnamed-chunk-7-1.pdf}

The box plots are all largely symmetrical, with a mean roughly around
zero (which will be explored more in detail next). The horizontal lines
mark outliers for each ot the plots, from them it can be that values
larger or smaller than 0.01 is not common. It can also be seen that VAW
has the largest deviation from the mean, followed by IWN, then SPY and
AGG has the least fluctuation.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Calculation number of observations, sample mean and variance for the four ETF\textquotesingle{}s. }

\CommentTok{\# Code below has been commented out to avoid clutter in the document. Results }
\CommentTok{\# has been been filled out in the table. }

\CommentTok{\# sum(!is.na(D$AGG))}
\CommentTok{\# var(D$AGG, na.rm=TRUE)}
\CommentTok{\# sd(D$AGG, na.rm=TRUE)}
\CommentTok{\# summary(D$AGG, na.rm=TRUE)}
\CommentTok{\# }
\CommentTok{\# sum(!is.na(D$VAW))}
\CommentTok{\# var(D$VAW, na.rm=TRUE)}
\CommentTok{\# sd(D$VAW, na.rm=TRUE)}
\CommentTok{\# summary(D$VAW, na.rm=TRUE)}
\CommentTok{\# }
\CommentTok{\# sum(!is.na(D$IWN))}
\CommentTok{\# var(D$IWN, na.rm=TRUE)}
\CommentTok{\# sd(D$IWN, na.rm=TRUE)}
\CommentTok{\# summary(D$IWN, na.rm=TRUE)}
\CommentTok{\# }
\CommentTok{\# sum(!is.na(D$SPY))}
\CommentTok{\# var(D$SPY, na.rm=TRUE)}
\CommentTok{\# sd(D$SPY, na.rm=TRUE)}
\CommentTok{\# summary(D$SPY, na.rm=TRUE)}
\end{Highlighting}
\end{Shaded}

\begin{table}[]
  \begin{center}
    \begin{tabular}{|l|l|l|l|l|l|l|l|}
    \hline
      ETF & Number of obs. & Sample mean & Sample variance & Std. dev. & Lower quantile & Median    & Upper quantile \\ \hline
          & n              & (x)         & ($s^2$)         & (s)       & $(Q_1)$        & $(Q_2)$   & $(Q_3)$        \\ \hline
      AGG & 454            & 0.0002658   & 3.571e-05       & 0.005976  & -0.002973      & 0.0002374 & 0.003893       \\ \hline
      VAW & 454            & 0.001794    & 0.001302        & 0.03608   & -0.01610       & 0.004798  & 0.019685       \\ \hline
      IWN & 454            & 0.001188    & 0.001025        & 0.03202   & -0.01431       & 0.003120  & 0.019056       \\ \hline
      SPY & 454            & 0.001360    & 0.0006143       & 0.02479   & -0.01133       & 0.004216  & 0.014498       \\ \hline
    \end{tabular}
  \end{center}
  \caption{Summary statistics}
\end{table}

From the table the quantiles can be read more precisely than from the
box plot, also the mean, variance and standard deviation can be seen.

\section{Statistical analysis}

Below are QQ plots for the four ETF's.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qqnorm}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{AGG, }\AttributeTok{main=}\StringTok{"AGG"}\NormalTok{, }\AttributeTok{col=}\StringTok{"blue"}\NormalTok{)}
\FunctionTok{qqline}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{AGG, }\AttributeTok{col=}\StringTok{"blue"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_finans_files/figure-latex/unnamed-chunk-9-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qqnorm}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{VAW, }\AttributeTok{main=}\StringTok{"VAW"}\NormalTok{, }\AttributeTok{col=}\StringTok{"red"}\NormalTok{)}
\FunctionTok{qqline}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{VAW, }\AttributeTok{col=}\StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_finans_files/figure-latex/unnamed-chunk-9-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qqnorm}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{IWN, }\AttributeTok{main=}\StringTok{"IWN"}\NormalTok{, }\AttributeTok{col=}\StringTok{"green"}\NormalTok{)}
\FunctionTok{qqline}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{IWN, }\AttributeTok{col=}\StringTok{"green"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_finans_files/figure-latex/unnamed-chunk-9-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qqnorm}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{SPY, }\AttributeTok{main=}\StringTok{"SPY"}\NormalTok{, }\AttributeTok{col=}\StringTok{"orange"}\NormalTok{)}
\FunctionTok{qqline}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{SPY, }\AttributeTok{col=}\StringTok{"orange"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_finans_files/figure-latex/unnamed-chunk-9-4.pdf}

From the plots it can be clearly seen that they mostly follow a normal
distribution. However the data also show that the tails of the data has
a greater variation than what would be expected of a true normal
distribution. In the investment world this is known as ``fat tails'',
which are returns that are wildly higher or lower than expected.

Let's examine the VAW ETF, which has the highest mean return and
standard deviation of the funds.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#VAW: expected weekly return = 0.1794\%, standard deviation = 3.608\%}
\NormalTok{mean\_vaw }\OtherTok{=} \FloatTok{0.001794}
\NormalTok{sd\_vaw }\OtherTok{=} \FloatTok{0.03608}

\FunctionTok{hist}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{VAW, }\AttributeTok{xlab=}\StringTok{"Return (VAW)"}\NormalTok{, }\AttributeTok{prob=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{breaks =} \DecValTok{100}\NormalTok{)}

\CommentTok{\#Theoretical normal distribution}
\NormalTok{x }\OtherTok{=} \FunctionTok{seq}\NormalTok{(}\AttributeTok{from =} \FunctionTok{min}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{VAW), }\AttributeTok{to =} \FunctionTok{max}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{VAW), }\AttributeTok{by=}\FloatTok{0.001}\NormalTok{)}
\NormalTok{y }\OtherTok{=} \FunctionTok{dnorm}\NormalTok{(x, mean\_vaw, sd\_vaw)}
\FunctionTok{lines}\NormalTok{(x, y, }\AttributeTok{col=}\StringTok{"red"}\NormalTok{)}

\CommentTok{\#Vertical lines highlighting 1,2,3 standard deviations to each side and the mean.}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \FunctionTok{seq}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{3}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{1}\NormalTok{)) \{}
  \FunctionTok{abline}\NormalTok{(}\AttributeTok{v =}\NormalTok{ mean\_vaw }\SpecialCharTok{+}\NormalTok{ i}\SpecialCharTok{*}\NormalTok{sd\_vaw, }\AttributeTok{col=}\StringTok{"blue"}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_finans_files/figure-latex/unnamed-chunk-10-1.pdf}

From this plot it can be quite clearly seen that there are a few very
high returns but also a few very big losses, which both are quite
surprising for a normal distribution. Let's examine the probability of
the biggest loss:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{loss\_vaw }\OtherTok{=} \FunctionTok{min}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{VAW)}
\NormalTok{loss\_vaw}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.2036603
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Number of standard distributions out:}
\NormalTok{distributions\_out }\OtherTok{=}\NormalTok{ loss\_vaw}\SpecialCharTok{/}\NormalTok{sd\_vaw}
\NormalTok{distributions\_out}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -5.644687
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#So the biggest loss of 20.4\% in a week is almost 6 standard deviations out!}

\CommentTok{\#The probability if this happening in a standard deviation is:}
\FunctionTok{pnorm}\NormalTok{(loss\_vaw, }\AttributeTok{mean =}\NormalTok{ mean\_vaw, }\AttributeTok{sd =}\NormalTok{ sd\_vaw)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6.189954e-09
\end{verbatim}

Obviously the chance of this event occurring is ridiculously small, but
even though this is not an uncommon occurrence in investing. Even
though, when reading about the subject it is widely considered that the
normal distribution is the best available model. Maybe a lack of data or
other factors plays into the results, or maybe there is some other
better model that has not been found yet.

\subsection{Confidence interval}

The formula for the one-sample mean confidence interval is:

\[ \overline{x} = t_{1-\alpha /2} \cdot \frac{s}{\sqrt{n}} \]

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Calculated "by hand":}
\NormalTok{mean\_agg }\OtherTok{=} \FunctionTok{mean}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{AGG)}
\NormalTok{sd\_agg }\OtherTok{=} \FunctionTok{sd}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{AGG)}
\NormalTok{mean\_agg }\SpecialCharTok{+} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{) }\SpecialCharTok{*} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\FunctionTok{length}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{AGG) }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{*}\NormalTok{ (sd\_agg }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{length}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{AGG)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.0002854073  0.0008169213
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Using built{-}in R function}
\FunctionTok{t.test}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{AGG, }\AttributeTok{conf.level =} \FloatTok{0.95}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  D$AGG
## t = 0.94757, df = 453, p-value = 0.3439
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -0.0002854073  0.0008169213
## sample estimates:
##   mean of x 
## 0.000265757
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#t.test(D$VAW, conf.level=0.95)}
\CommentTok{\#t.test(D$IWN, conf.level=0.95)}
\CommentTok{\#t.test(D$SPY, conf.level=0.95)}
\end{Highlighting}
\end{Shaded}

As it can be seen, the values calculated ``by hand'' are the same as
from the t.test functionality in R.

Below can be seen the confidence intervals calculated for the other
ETF's.

\begin{table}[]
  \begin{center}
    \begin{tabular}{|l|l|l|}
    \hline
          & Lower bound of CI & Upper bound of CI \\ \hline
      AGG & -0.0002854        & 0.0008169         \\ \hline
      VAW & -0.001534         & 0.005122          \\ \hline
      IWN & -0.001765         & 0.004141          \\ \hline
      SPY & -0.0009260        & 0.003646          \\ \hline
    \end{tabular}
  \end{center}
  \caption{Confidence intervals}
\end{table}

\subsection{Null-hypothesis test}

In general we say that the null-hypothesis is rejected if the p-value is
smaller than 0.05. The smaller the p-value, the stronger the evidence
against \(H_0\).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Using formula 3.23 to calculate the P{-}value}
\NormalTok{t\_obs }\OtherTok{=}\NormalTok{ (mean\_agg }\SpecialCharTok{{-}} \DecValTok{0}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ (sd\_agg }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{length}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{AGG)))}
\DecValTok{2} \SpecialCharTok{*}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}}\FunctionTok{pt}\NormalTok{(t\_obs, }\AttributeTok{df=}\FunctionTok{length}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{AGG)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.3438511
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Same results as before, but this time we\textquotesingle{}re specifying mu. Doesn\textquotesingle{}t make a difference though. }
\FunctionTok{t.test}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{AGG, }\AttributeTok{mu=}\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  One Sample t-test
## 
## data:  D$AGG
## t = 0.94757, df = 453, p-value = 0.3439
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -0.0002854073  0.0008169213
## sample estimates:
##   mean of x 
## 0.000265757
\end{verbatim}

From the results it can be seen that the manual calculation is correct
when compared to the built-in R function. It can also be seen that with
a P-value = 0.344 there is little or no evidence against \(H_0\)
(consulting table 3.1 in the course notes).

This can also be seen from the confidence intervals, since they describe
the interval in which the true mean might be. Since the lower bound for
the confidence interval for AGG (and the other ETF's for that matter) is
below zero, it cannot be determined if the actual mean might actually be
zero.

\subsection{Welch two-sample test}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#method 3.51 p 172, using theorem 3.50}
\NormalTok{n\_agg }\OtherTok{=} \FunctionTok{length}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{AGG); n\_vaw }\OtherTok{=} \FunctionTok{length}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{VAW)}
\CommentTok{\#mean\_agg; sd\_agg; n\_agg}
\CommentTok{\#mean\_vaw; sd\_vaw; n\_vaw}

\NormalTok{t\_obs }\OtherTok{=}\NormalTok{ ( (mean\_vaw }\SpecialCharTok{{-}}\NormalTok{ mean\_agg) }\SpecialCharTok{{-}} \DecValTok{0}\NormalTok{) }\SpecialCharTok{/} \FunctionTok{sqrt}\NormalTok{( (sd\_agg}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}\SpecialCharTok{/}\NormalTok{n\_agg }\SpecialCharTok{+}\NormalTok{ (sd\_vaw}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}\SpecialCharTok{/}\NormalTok{n\_vaw )}
\NormalTok{v }\OtherTok{=}\NormalTok{ ( (sd\_agg}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\NormalTok{n\_agg) }\SpecialCharTok{+}\NormalTok{ (sd\_vaw}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\NormalTok{n\_vaw) )}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{/}
\NormalTok{  ( (sd\_agg}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\NormalTok{n\_agg)}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{/}\NormalTok{ (n\_agg}\DecValTok{{-}1}\NormalTok{) }\SpecialCharTok{+}\NormalTok{ (sd\_vaw}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\NormalTok{n\_vaw)}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{/}\NormalTok{ (n\_vaw}\DecValTok{{-}1}\NormalTok{) )}

\NormalTok{t\_obs; v; }\DecValTok{2}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{pt}\NormalTok{(t\_obs, v))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8903836
\end{verbatim}

\begin{verbatim}
## [1] 477.8351
\end{verbatim}

\begin{verbatim}
## [1] 0.373708
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{VAW, D}\SpecialCharTok{$}\NormalTok{AGG)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Welch Two Sample t-test
## 
## data:  D$VAW and D$AGG
## t = 0.89019, df = 477.83, p-value = 0.3738
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.001844827  0.004900893
## sample estimates:
##   mean of x   mean of y 
## 0.001793790 0.000265757
\end{verbatim}

It can be seen that the values between manual calculation and built-in R
functions are the same. The test was necessary to perform since the
confidence intervals were overlapping, and the result of the test might
have shown that the null-hypothesis could have been rejected anyway.
However, since the P-value is (significantly) larger than 0.05, it
can't.

\subsection{Correlation}

The formula for the sample correlation coefficient (\(r\)) and the
sample covariance (\(s_{xy}\)):

\[r = \frac{s_{xy}}{s_x \cdot s_y}\]

\[ s_{xy} = \frac{1}{n-1} \sum\limits_{i=1}^{n} \left( \frac{x_i-\overline{x}}{s_x} \right) \left(\frac{y_i-\overline{y}}{s_y} \right) \]

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Values for the covariance formula:}
\FunctionTok{cov}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{VAW, D}\SpecialCharTok{$}\NormalTok{IWN); }\FunctionTok{sd}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{VAW); }\FunctionTok{sd}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{IWN)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.0009838237
\end{verbatim}

\begin{verbatim}
## [1] 0.03608286
\end{verbatim}

\begin{verbatim}
## [1] 0.03201547
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{r }\OtherTok{=}\NormalTok{ (}\FloatTok{0.0009838237}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ (}\FloatTok{0.03608286} \SpecialCharTok{*} \FloatTok{0.03201547}\NormalTok{)}
\NormalTok{r}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8516408
\end{verbatim}

So the covariance between the two ETF's is 0.8516408. When comparing to
the R function, it can be seen that it is the same calculated value.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Computing the correlation between selected ETF\textquotesingle{}s}
\FunctionTok{cor}\NormalTok{(D[ ,}\FunctionTok{c}\NormalTok{(}\StringTok{"AGG"}\NormalTok{,}\StringTok{"VAW"}\NormalTok{,}\StringTok{"IWN"}\NormalTok{,}\StringTok{"SPY"}\NormalTok{)], }\AttributeTok{use=}\StringTok{"pairwise.complete.obs"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            AGG        VAW        IWN        SPY
## AGG  1.0000000 -0.1975679 -0.1352621 -0.2187164
## VAW -0.1975679  1.0000000  0.8516407  0.8863608
## IWN -0.1352621  0.8516407  1.0000000  0.9100966
## SPY -0.2187164  0.8863608  0.9100966  1.0000000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ylim }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\FloatTok{0.2}\NormalTok{,}\FloatTok{0.2}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(}\FunctionTok{c}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{t, D}\SpecialCharTok{$}\NormalTok{t), }\FunctionTok{c}\NormalTok{(D}\SpecialCharTok{$}\NormalTok{VAW, D}\SpecialCharTok{$}\NormalTok{IWN), }\AttributeTok{type=}\StringTok{"p"}\NormalTok{, }\AttributeTok{ylim=}\NormalTok{ylim, }\AttributeTok{xlab=}\StringTok{"Date"}\NormalTok{, }
     \AttributeTok{ylab=}\StringTok{"Return"}\NormalTok{, }\AttributeTok{col=}\FunctionTok{c}\NormalTok{(}\StringTok{"red"}\NormalTok{, }\StringTok{"green"}\NormalTok{), }\AttributeTok{cex=}\FloatTok{0.4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{project_finans_files/figure-latex/unnamed-chunk-17-1.pdf}

From the scatterplot it can be seen that if we drew a trendline between
the two data sets, the points would fluctuate relatively evenly around
that straight line. This is also what we would expect from a covariance
of 0.85.

\end{document}
